source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!

pod 'ReactiveCocoa'
pod 'AFNetworking'
pod 'MJExtension'
pod 'MJRefresh'
pod 'MBProgressHUD'

target :V2EXObjCTests, :exclusive => true do
    pod 'Kiwi'
end
